# docker-compose.yml
version: '3'
networks:
  myapp-network:
services:
  # main application
  myapp:
    container_name: myapp
    build:
      .
    depends_on:
      - "myapp-celery"
    networks:
      - myapp-network
    ports:
      - "8000:8000"
  # broker for async communication
  myapp-rabbitmq:
    container_name: myapp-rabbitmq
    image: rabbitmq
    networks:
      - myapp-network
    expose:
      - "5672"
  # cache for storing async results
  myapp-redis:
    container_name: myapp-redis
    image: redis
    networks:
      - myapp-network
    expose:
      - "6379"
  # worker for async data processing
  myapp-celery:
    container_name: myapp-celery
    build:
      context: .
      dockerfile: ./cl/Dockerfile
    depends_on:
      - "myapp-redis"
      - "myapp-rabbitmq"
    networks:
      - myapp-network
